---
abstract: 'A template provider that uses DBIC for database access and exhibits fallback functionality'
author:
  - 'Rob Hoelz <rhoelz@inoc.com>'
build_requires:
  DBD::SQLite: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200005, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Provider-PrefixDBIC
requires:
  DBIx::Class: 0
  Template: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Template-Provider-PrefixDBIC
version: 0.01
